const TYPE_REPORT_INDIVIDUAL = 0;
const TYPE_REPORT_BRANCH = 1;
const TYPE_REPORT_GLOBAL = 2;
const TYPE_REPORT_PROJECT_DETAIL_INDIVIDUAL = 3;
const TYPE_REPORT_PROJECT_DETAIL_BRANCH = 4;
const TYPE_REPORT_PROJECT_INDIVIDUAL = 5;
export {
  TYPE_REPORT_INDIVIDUAL,
  TYPE_REPORT_BRANCH,
  TYPE_REPORT_GLOBAL,
  TYPE_REPORT_PROJECT_DETAIL_INDIVIDUAL,
  TYPE_REPORT_PROJECT_DETAIL_BRANCH,
  TYPE_REPORT_PROJECT_INDIVIDUAL,
};
